version: '3'
services:

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 30s

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory 1024mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_USERNAME=${REDIS_USERNAME}

  app:
    build: .
    ports:
      - "8000:8000"
    container_name: app
    restart: always
    volumes:
      - .:/app
    depends_on:
      - redis
      - mysql
    env_file:
      - ./.env
  
  redis_consumer:
    build:
      context: .
      dockerfile: redis_main.Dockerfile
    command: python3 -m app.services.redis_main
    container_name: redis_consumer
    restart: always
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - ./.env
  
  redis_consumer2:
    build:
      context: .
      dockerfile: redis_main.Dockerfile
    command: python3 -m app.services.redis_main
    container_name: redis_consumer2
    restart: always
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - ./.env
  
  redis_consumer3:
    build:
      context: .
      dockerfile: redis_main.Dockerfile
    command: python3 -m app.services.redis_main
    container_name: redis_consumer3
    restart: always
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - ./.env

  redis_service_delayed_msgs:
    build:
      context: .
      dockerfile: delayed_msgs.Dockerfile
    container_name: redis_service_delayed_msgs
    restart: always
    command: python3 delayed_msgs.py
    depends_on:
      - redis
    env_file:
      - ./.env

volumes:
  mysql_data:
  redis_data:
