---
- name: Install packages and Docker
  hosts: all
  user: kalkulus
  become: true
  tasks:
    - name: Install basic packages
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
          - curl
          - nginx
          - certbot
          - python3-certbot-nginx

    - name: Install Python dependencies for docker-compose
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
          - libffi-dev
          - libssl-dev
          - python3-dev
          - python3
          - python3-pip

    - name: Install Docker using official script
      shell: curl -fsSL https://get.docker.com | sh
      args:
        creates: /usr/bin/docker

    - name: Verify Docker installation
      command: docker --version
      register: docker_version
      changed_when: false

    - name: Print Docker version
      debug:
        var: docker_version.stdout

    - name: Install Docker Compose
      pip:
        name: docker-compose
        state: present

    - name: Verify Docker Compose installation
      command: docker-compose --version
      register: docker_compose_version
      changed_when: false

    - name: Print Docker Compose version
      debug:
        var: docker_compose_version.stdout

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
